### ISSUE TITLE
ember-cli-deploy 0.5.0 and ember-cli-deploy-json-config

### ISSUE THREAD

**Issue by himynameisjonas** [elucid/ember-cli-redis-proxy#7]
Hi, I'm trying out ember-cli-deploy 0.5.0 on a new ember app and sadly noticed that this package doesn't work anymore :(

It was quite easy to this lib to read the new config format but I wonder if it's possible to get it to work with [ember-cli-deploy-json-config](https://github.com/ember-cli-deploy/ember-cli-deploy-json-config) (converts the index.html to json for easier parsing in my Rails app that is serving the ember app)

**Comment by elucid** [comment]
This plugin won't be updated to be compatible with ember-cli-deploy as the functionality is now built into core. Please see http://ember-cli.github.io/ember-cli-deploy/docs/v0.5.x/development-workflow/ for details.
